### ISSUE TITLE
About voice tools

### ISSUE THREAD

**Issue by YacratesWyh** [BrasD99/HeyGenClone#4]
Need some recommend of this. Definitely coqui-ai is not a good choice. Maybe **sovits** could be one. **VaLLE** needs further development or support.

**Comment by BrasD99** [comment]
Hi, @YacratesWyh!

At the moment, I have studied many solutions for voice cloning. I agree that the solution from Coqui is not optimal, because it does not preserve the intonation of speech, and often the result of cloning is very different from the original voice. At the moment, I paid attention to the XTTS - a new model from Coqui, you can try it at this [link](https://huggingface.co/spaces/coqui/xtts). I don't have time to train my own model. However, it is necessary that there is a voice cloning functionality in different languages. Besides, I am currently the only contributor, it is physically impossible for one person to do everything in one unit of time. Therefore, as I write everywhere, I will be glad to new people who can help develop the project!

If you have any additional questions or suggestions for the development of the project, I will be glad to see you in our Telegram group: https://t.me/+IlOPXyNkscxhZjJi

**Comment by BrasD99** [comment]
I also found the perfect model for voice cloning, it does what we need. Its name: [MegaTTS 2](https://mega-tts.github.io/mega2_demo/). However, it is in private access.
